language: cpp

matrix:
  include:
    #
    # GCC
    #

    # works on Precise and Trusty
    - os: linux
      dist: xenial
      compiler: g++-9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - TOOLSET=gcc
        - TARGETS="pwiz pwiz_tools/Bumbershoot"
        - MATRIX_EVAL="TOOLSET=toolset=gcc-9"

    #
    # Clang
    #

    # works on Precise and Trusty
    - os: linux
      dist: xenial
      compiler: clang++-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - TARGETS="pwiz pwiz_tools/Bumbershoot"
        - MATRIX_EVAL="TOOLSET=toolset=clang-3.6"

    # works on Trusty
    - os: linux
      dist: xenial
      compiler: clang++-7
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      env:
        - TARGETS="pwiz pwiz_tools/Bumbershoot"
        - MATRIX_EVAL="TOOLSET=toolset=clang-7"

    - os: osx
      osx_image: xcode8.3
      env:
         - TARGETS="pwiz"
#        - MATRIX_EVAL="TOOLSET=toolset=gcc-4.9"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc5 && TOOLSET=toolset=gcc-5"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc6 && TOOLSET=toolset=gcc-6"

#    - os: osx
#      osx_image: xcode8
#      env:
#        - MATRIX_EVAL="brew install gcc && TOOLSET=toolset=gcc-7"

before_install:
    - eval "${MATRIX_EVAL}"

script: ./quickbuild.sh --abbreviate-paths -j2 $(TARGETS)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b964b972d7ac96afd45c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
